### Get tasks

GET http://localhost:3001/

### Add new task
POST http://localhost:3001/new
Content-Type: application/json

{
    "description": "Test from My server"
}

### Delete task
DELETE http://localhost:3001/delete/11